package com.gun.common.entity;
// Generated 2017-6-1 18:10:41 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;

import com.gun.common.pojo.ValueObject;

/**
 * LotteryRule generated by hbm2java
 */
public class Advertisement extends ValueObject<Integer> {

	/**
	 * 序列号
	 */
	private static final long serialVersionUID = 8888089501934905376L;
	private Integer id;
	private String adverName;
	private byte[] adverImg;
	private String adverURL;
	private String supplier;
	private Integer priority;
	private String validityStartDate;
	private String validityEndDate;
	private Date createDate;
	private String imageURL;
	private String createById;
	private Serializable createdByName;
	private String updatedById;
	private Serializable updatedByName;
	private Date updatedDate;
	private String approveState;
	private String approveStateName;
	
	public Advertisement() {
		super();
	}
	
	public Advertisement(Integer id) {
		super(id);
	}

	public Advertisement(Integer id, String adverName, byte[] adverImg, String adverURL, String supplier,
			Integer priority, String validityStartDate, String validityEndDate, Date createDate, String imageURL,
			String createById, Serializable createdByName, String updatedById, Serializable updatedByName,
			Date updatedDate, String approveState, String approveStateName) {
		super();
		this.id = id;
		this.adverName = adverName;
		this.adverImg = adverImg;
		this.adverURL = adverURL;
		this.supplier = supplier;
		this.priority = priority;
		this.validityStartDate = validityStartDate;
		this.validityEndDate = validityEndDate;
		this.createDate = createDate;
		this.imageURL = imageURL;
		this.createById = createById;
		this.createdByName = createdByName;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.approveState = approveState;
		this.approveStateName = approveStateName;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAdverName() {
		return adverName;
	}

	public void setAdverName(String adverName) {
		this.adverName = adverName;
	}

	public byte[] getAdverImg() {
		return adverImg;
	}

	public void setAdverImg(byte[] adverImg) {
		this.adverImg = adverImg;
	}

	public String getAdverURL() {
		return adverURL;
	}

	public void setAdverURL(String adverURL) {
		this.adverURL = adverURL;
	}

	public String getSupplier() {
		return supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getValidityStartDate() {
		return validityStartDate;
	}

	public void setValidityStartDate(String validityStartDate) {
		this.validityStartDate = validityStartDate;
	}

	public String getValidityEndDate() {
		return validityEndDate;
	}

	public void setValidityEndDate(String validityEndDate) {
		this.validityEndDate = validityEndDate;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getImageURL() {
		return imageURL;
	}

	public void setImageURL(String imageURL) {
		this.imageURL = imageURL;
	}

	public String getCreateById() {
		return createById;
	}

	public void setCreateById(String createById) {
		this.createById = createById;
	}

	public Serializable getCreatedByName() {
		return createdByName;
	}

	public void setCreatedByName(Serializable createdByName) {
		this.createdByName = createdByName;
	}

	public String getUpdatedById() {
		return updatedById;
	}

	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	public Serializable getUpdatedByName() {
		return updatedByName;
	}

	public void setUpdatedByName(Serializable updatedByName) {
		this.updatedByName = updatedByName;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getApproveState() {
		return approveState;
	}

	public void setApproveState(String approveState) {
		this.approveState = approveState;
	}

	public String getApproveStateName() {
		return approveStateName;
	}

	public void setApproveStateName(String approveStateName) {
		this.approveStateName = approveStateName;
	}

}
