package com.gun.common.entity.pojo;

import java.io.Serializable;
import java.util.Date;

import com.gun.common.pojo.ValueObject;

/**
 * SysUserInfo generated by hbm2java
 */
public class AdvertisementDTO extends ValueObject<Integer> {

	/**
	 * 序列号
	 */
	private static final long serialVersionUID = -7272710482768404566L;
	
	//枚举
	public static enum ATTRIBUTE {
		ID("id"),
		ADVERT_NAME("adverName"),
		ADVERT_IMG("adverImg"),
		ADVERT_URL("adverURL"),
		SUPPLIER("supplier"),
		PRIORITY("priority"),
		VALIDITY_START_DATE("validityStartDate"),
		VALIDITY_END_DATE("validityEndDate"),
		CREAT_DATE("createDate"),
		CREATE_BY_ID("createById"),
		CREATED_BY_NAME("createdByName"),
		UPDATED_BY_ID("updatedById"),
		UPDATED_BY_NAME("updatedByName"),
		UPDATED_DATE("updatedDate"),
		APPROVE_STATE("approveState"),
		APPROVE_STATE_NAME("approveStateName"),
		IMAGE_URL("imageURL")
	    ;
	    private String value;
	    ATTRIBUTE(String value) {
	      this.value = value;
	    };
	    public String getValue() {
	      return this.value;
	    }
	};

	private String adverName;
	private byte[] adverImg;
	private String adverURL;
	private String supplier;//广告商
	private Integer priority;//优先
	private String priorityName;
	private String validityStartDate;
	private String validityEndDate;
	private Date createDate;
	private String imageURL;
	private String createById;
	private Serializable createdByName;
	private String updatedById;
	private Serializable updatedByName;
	private Date updatedDate;
	private String approveState;
	private String approveStateName;
	
	/**
	 * Constructor:无参构造
	 */
	public AdvertisementDTO() {
		super();
	}

	/**
	 * Constructor:有参构造
	 */
	public AdvertisementDTO(String adverName, byte[] adverImg, String adverURL, String supplier, Integer priority,
			String validityStartDate, String validityEndDate, Date createDate, String imageURL, String createById,
			Serializable createdByName, String updatedById, Serializable updatedByName, Date updatedDate,String priorityName,
			String approveState, String approveStateName) {
		super();
		this.adverName = adverName;
		this.adverImg = adverImg;
		this.adverURL = adverURL;
		this.supplier = supplier;
		this.priority = priority;
		this.validityStartDate = validityStartDate;
		this.validityEndDate = validityEndDate;
		this.createDate = createDate;
		this.imageURL = imageURL;
		this.createById = createById;
		this.createdByName = createdByName;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.approveState = approveState;
		this.approveStateName = approveStateName;
		this.priorityName = priorityName;
	}

	/**
	 * @return the adverName
	 */
	public String getAdverName() {
		return adverName;
	}

	/**
	 * @param adverName the adverName to set
	 */
	public void setAdverName(String adverName) {
		this.adverName = adverName;
	}

	/**
	 * @return the adverImg
	 */
	public byte[] getAdverImg() {
		return adverImg;
	}

	/**
	 * @param adverImg the adverImg to set
	 */
	public void setAdverImg(byte[] adverImg) {
		this.adverImg = adverImg;
	}

	/**
	 * @return the adverURL
	 */
	public String getAdverURL() {
		return adverURL;
	}

	/**
	 * @param adverURL the adverURL to set
	 */
	public void setAdverURL(String adverURL) {
		this.adverURL = adverURL;
	}

	/**
	 * @return the supplier
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * @param supplier the supplier to set
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	/**
	 * @return the priority
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * @param priority the priority to set
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * @return the validityStartDate
	 */
	public String getValidityStartDate() {
		return validityStartDate;
	}

	/**
	 * @param validityStartDate the validityStartDate to set
	 */
	public void setValidityStartDate(String validityStartDate) {
		this.validityStartDate = validityStartDate;
	}

	/**
	 * @return the validityEndDate
	 */
	public String getValidityEndDate() {
		return validityEndDate;
	}

	/**
	 * @param validityEndDate the validityEndDate to set
	 */
	public void setValidityEndDate(String validityEndDate) {
		this.validityEndDate = validityEndDate;
	}

	/**
	 * @return the createDate
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * @param createDate the createDate to set
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * @return the imageURL
	 */
	public String getImageURL() {
		return imageURL;
	}

	/**
	 * @param imageURL the imageURL to set
	 */
	public void setImageURL(String imageURL) {
		this.imageURL = imageURL;
	}

	/**
	 * @return the createById
	 */
	public String getCreateById() {
		return createById;
	}

	/**
	 * @param createById the createById to set
	 */
	public void setCreateById(String createById) {
		this.createById = createById;
	}

	/**
	 * @return the createdByName
	 */
	public Serializable getCreatedByName() {
		return createdByName;
	}

	/**
	 * @param createdByName the createdByName to set
	 */
	public void setCreatedByName(Serializable createdByName) {
		this.createdByName = createdByName;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public Serializable getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(Serializable updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the approveState
	 */
	public String getApproveState() {
		return approveState;
	}

	/**
	 * @param approveState the approveState to set
	 */
	public void setApproveState(String approveState) {
		this.approveState = approveState;
	}

	/**
	 * @return the approveStateName
	 */
	public String getApproveStateName() {
		return approveStateName;
	}

	/**
	 * @param approveStateName the approveStateName to set
	 */
	public void setApproveStateName(String approveStateName) {
		this.approveStateName = approveStateName;
	}

	/**
	 * @return the priorityName
	 */
	public String getPriorityName() {
		return priorityName;
	}

	/**
	 * @param priorityName the priorityName to set
	 */
	public void setPriorityName(String priorityName) {
		this.priorityName = priorityName;
	}

}
