package com.gun.common.entity.pojo;
// Generated 2017-8-17 12:01:22 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

import com.gun.common.pojo.ValueObject;

/**
 * CheckTicketRecord generated by hbm2java
 */
public class CheckTicketRecordDTO extends ValueObject<BigDecimal> {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6230966135490274209L;

	public static enum ATTRIBUTE {
		ID("id"),
		ANDROID_USER_ID("androidUserId"),
		ROUND("round"),
		LETTER("letter"),
		BEGIN_NUMBER("beginNumber"),
		END_NUMBER("endNumber"),
		WINNIN_SUM("winninSum"),
		CREATED_DATE("createdDate");
		private String value;
		ATTRIBUTE(String value) {
			this.value = value;
		};
		public String getValue() {
			return this.value;
		}
	}
	
	private BigDecimal androidUserId;
	private String round;
	private String letter;
	private String beginNumber;
	private String endNumber;
	private BigDecimal winninSum;
	private Date createdDate;
	private String androidUserName;

	public CheckTicketRecordDTO() {
	}

	public BigDecimal getAndroidUserId() {
		return androidUserId;
	}

	public void setAndroidUserId(BigDecimal androidUserId) {
		this.androidUserId = androidUserId;
	}

	public String getRound() {
		return round;
	}

	public void setRound(String round) {
		this.round = round;
	}

	public String getLetter() {
		return letter;
	}

	public void setLetter(String letter) {
		this.letter = letter;
	}

	public String getBeginNumber() {
		return beginNumber;
	}

	public void setBeginNumber(String beginNumber) {
		this.beginNumber = beginNumber;
	}

	public String getEndNumber() {
		return endNumber;
	}

	public void setEndNumber(String endNumber) {
		this.endNumber = endNumber;
	}

	public BigDecimal getWinninSum() {
		return winninSum;
	}

	public void setWinninSum(BigDecimal winninSum) {
		this.winninSum = winninSum;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getAndroidUserName() {
		return androidUserName;
	}

	public void setAndroidUserName(String androidUserName) {
		this.androidUserName = androidUserName;
	}

}
