package com.gun.common.entity.pojo;
// Generated 2017-7-5 9:47:48 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

import com.gun.common.pojo.ValueObject;

/**
 * AndroidUser generated by hbm2java
 */
public class CustomerWinningDTO extends ValueObject<BigDecimal> {
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -45257167823443581L;

	public static enum ATTRIBUTE {
		PERIOD("period"),
		USERNAME("username"),
		FULL_NAME("fullName"),
		NRC("nrc"),
		MOBILE_NO("mobileNo"),
		LOTTERY_CATEGORY("lotteryCategory"),
		LOTTERY_CATEGORY_NAME("lotteryCategoryName"),
		SUB_CATEGORY_ID("subCategoryId"),
		SUB_CATEGORY_NAME("subCategoryName"),
		LOTTERY_NUMBER("lotteryNumber"),
		WINNING_GRADE("winninGrade"),
		WINNING_NAME("winninName"),
		WINNING_NUMBER("winninNumber"),
		WINNING_SUM("winninSum"),
		WINNING_ID("winninId");
		private String value;
		ATTRIBUTE(String value) {
			this.value = value;
		};
		public String getValue() {
			return this.value;
		}
	}

	private String period;
	private String username;
	private String fullName;
	private String nrc;
	private String mobileNo;
	private String lotteryCategory;
	private String lotteryCategoryName;
	private Integer subCategoryId;
	private String subCategoryName;
	private String lotteryNumber;
	private Integer winninGrade;
	private String winninName;
	private String winninNumber;
	private BigDecimal winninSum;
	private String winninId;

	public CustomerWinningDTO() {
	}

	public String getPeriod() {
		return period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getNrc() {
		return nrc;
	}

	public void setNrc(String nrc) {
		this.nrc = nrc;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getLotteryCategory() {
		return lotteryCategory;
	}

	public void setLotteryCategory(String lotteryCategory) {
		this.lotteryCategory = lotteryCategory;
	}

	public String getLotteryCategoryName() {
		return lotteryCategoryName;
	}

	public void setLotteryCategoryName(String lotteryCategoryName) {
		this.lotteryCategoryName = lotteryCategoryName;
	}

	public Integer getSubCategoryId() {
		return subCategoryId;
	}

	public void setSubCategoryId(Integer subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public String getSubCategoryName() {
		return subCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	public String getLotteryNumber() {
		return lotteryNumber;
	}

	public void setLotteryNumber(String lotteryNumber) {
		this.lotteryNumber = lotteryNumber;
	}

	public Integer getWinninGrade() {
		return winninGrade;
	}

	public void setWinninGrade(Integer winninGrade) {
		this.winninGrade = winninGrade;
	}

	public String getWinninName() {
		return winninName;
	}

	public void setWinninName(String winninName) {
		this.winninName = winninName;
	}

	public String getWinninNumber() {
		return winninNumber;
	}

	public void setWinninNumber(String winninNumber) {
		this.winninNumber = winninNumber;
	}

	public BigDecimal getWinninSum() {
		return winninSum;
	}

	public void setWinninSum(BigDecimal winninSum) {
		this.winninSum = winninSum;
	}

	public String getWinninId() {
		return winninId;
	}

	public void setWinninId(String winninId) {
		this.winninId = winninId;
	}
	
}
