package com.gun.common.entity.pojo;
// Generated 2017-6-1 18:10:41 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

import com.gun.common.pojo.ValueObject;

/**
 * SysUserInfo generated by hbm2java
 */
public class LotteryRuleDTO extends ValueObject<BigDecimal> {

	/**
	 * 序列号
	 */
	private static final long serialVersionUID = 5075432256619882892L;
	
	//枚举
	public static enum ATTRIBUTE {
		ID("id"),
		LETTER_ROLE("letterRole"),
		BEGIN_LETTER("beginLetter"),
		END_LETTER("endLetter"),
		NUMBER_ROLE("numberRole"),
		BEGIN_NUMBER("beginNumber"),
		END_NUMBER("endNumber"),
		ON_SALE("onSale"),
		OFF_SALE("offSale"),
		STATUS("status"),
		STATUSNAME("statusName"),
		LOTTERY_PERIODS("lotteryPeriods"),
		LOTTERY_CATEGORY("lotteryCategory"),
		LOTTERY_CATEGORY_NAME("lotteryCategoryName"),
		SUB_CATEGORY_ID("subCategoryId"),
		SUB_CATEGORY_NAME("subCategoryName"),
		CATEGORY_ID("categoryId"),
		LOTTERY_TIMES("lotteryTimes"),
	    CREATE_BY_ID("createById"),
	    CREATED_BY_NAME("createdByName"),
	    CREATED_DATE("createdDate"),
	    UPDATED_BYID("updatedById"),
	    UPDATED_BY_NAME("updatedByName"),
	    CATEGORY_IMAGE("categoryImage"),
	    CATEGORY_IMAGE_NAME("categoryImageName"),
	    EFFECTIVE_DATE("effectiveDate"),
	    SUBCATEGORY_EFFECTIVE_DATE("subcategoryEffectiveDate"),
	    LOTTERY_NUMBER("lotteryNumber"),
	    BATCH_STATUS("batchStatus"),
	    UPDATED_DATE("updatedDate"),
	    SALE_PRICE("salePrice")
	    ;
	    private String value;
	    ATTRIBUTE(String value) {
	      this.value = value;
	    };
	    public String getValue() {
	      return this.value;
	    }
	};
	private String letterRole;//字母规则
	private String numberRole;//数字规则
	private String onSale;//开售日期
	private String offSale;//停售日期
	private String status;//状态(规则的状态-编辑中/审核中/已审核)
	private String statusName;
	private String lotteryPeriods;//彩票期数
	private String lotteryCategory;//彩票类别
	private String lotteryCategoryName;
	private Integer subCategoryId;
	private String subCategoryName;
	private Integer categoryId;//类别id
	private String lotteryTimes;//开奖时间
	private String createById;//创建人id
	private String createdByName;//创建人name
	private String createdDate;//创建日期
	private String updatedById;//异动人id
	private String updatedByName;//异动人name
	private String updatedDate;//异动时间
	private String beginLetter;//开始字符
	private String endLetter;//结束字符
	private String beginNumber;//开始数字
	private String endNumber;//结束数字
	private byte[] categoryImage;
	private String categoryImageName;
	private String effectiveDate;
	private String subcategoryEffectiveDate;
	private String lotteryNumber;
	private String batchStatus;
	private Integer salePrice;
	
	/**
	 * 无参构造
	 */
	public LotteryRuleDTO() {
	}

	/**
	 * Constructor:有参构造
	 */
	public LotteryRuleDTO(String letterRole, String numberRole, String onSale, String offSale, String status,String lotteryNumber,
			String statusName, String lotteryPeriods, String lotteryCategory,String lotteryCategoryName, Integer subCategoryId,String batchStatus,
			String subCategoryName, Integer categoryId, String lotteryTimes, String createById, String createdByName,String subcategoryEffectiveDate,
			String createdDate, String updatedById, String updatedByName, String updatedDate, String beginLetter,String effectiveDate,
			String endLetter, String beginNumber, String endNumber, byte[] categoryImage, String categoryImageName) {
		super();
		this.letterRole = letterRole;
		this.numberRole = numberRole;
		this.onSale = onSale;
		this.offSale = offSale;
		this.status = status;
		this.statusName = statusName;
		this.lotteryPeriods = lotteryPeriods;
		this.lotteryCategory = lotteryCategory;
		this.lotteryCategoryName = lotteryCategoryName;
		this.subCategoryId = subCategoryId;
		this.subCategoryName = subCategoryName;
		this.categoryId = categoryId;
		this.lotteryTimes = lotteryTimes;
		this.createById = createById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.beginLetter = beginLetter;
		this.endLetter = endLetter;
		this.beginNumber = beginNumber;
		this.endNumber = endNumber;
		this.categoryImage = categoryImage;
		this.categoryImageName = categoryImageName;
		this.effectiveDate = effectiveDate;
		this.subcategoryEffectiveDate = subcategoryEffectiveDate;
		this.lotteryNumber = lotteryNumber;
		this.batchStatus = batchStatus;
	}

	/**
	 * @return the letterRole
	 */
	public String getLetterRole() {
		return letterRole;
	}

	/**
	 * @param letterRole the letterRole to set
	 */
	public void setLetterRole(String letterRole) {
		this.letterRole = letterRole;
	}

	/**
	 * @return the numberRole
	 */
	public String getNumberRole() {
		return numberRole;
	}

	/**
	 * @param numberRole the numberRole to set
	 */
	public void setNumberRole(String numberRole) {
		this.numberRole = numberRole;
	}

	/**
	 * @return the onSale
	 */
	public String getOnSale() {
		return onSale;
	}

	/**
	 * @param onSale the onSale to set
	 */
	public void setOnSale(String onSale) {
		this.onSale = onSale;
	}

	/**
	 * @return the offSale
	 */
	public String getOffSale() {
		return offSale;
	}

	/**
	 * @param offSale the offSale to set
	 */
	public void setOffSale(String offSale) {
		this.offSale = offSale;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the statusName
	 */
	public String getStatusName() {
		return statusName;
	}

	/**
	 * @param statusName the statusName to set
	 */
	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
	 * @return the lotteryPeriods
	 */
	public String getLotteryPeriods() {
		return lotteryPeriods;
	}

	/**
	 * @param lotteryPeriods the lotteryPeriods to set
	 */
	public void setLotteryPeriods(String lotteryPeriods) {
		this.lotteryPeriods = lotteryPeriods;
	}

	/**
	 * @return the lotteryCategory
	 */
	public String getLotteryCategory() {
		return lotteryCategory;
	}

	/**
	 * @param lotteryCategory the lotteryCategory to set
	 */
	public void setLotteryCategory(String lotteryCategory) {
		this.lotteryCategory = lotteryCategory;
	}

	/**
	 * @return the subCategoryId
	 */
	public Integer getSubCategoryId() {
		return subCategoryId;
	}

	/**
	 * @param subCategoryId the subCategoryId to set
	 */
	public void setSubCategoryId(Integer subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	/**
	 * @return the subCategoryName
	 */
	public String getSubCategoryName() {
		return subCategoryName;
	}

	/**
	 * @param subCategoryName the subCategoryName to set
	 */
	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	/**
	 * @return the categoryId
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * @param categoryId the categoryId to set
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * @return the lotteryTimes
	 */
	public String getLotteryTimes() {
		return lotteryTimes;
	}

	/**
	 * @param lotteryTimes the lotteryTimes to set
	 */
	public void setLotteryTimes(String lotteryTimes) {
		this.lotteryTimes = lotteryTimes;
	}

	/**
	 * @return the createById
	 */
	public String getCreateById() {
		return createById;
	}

	/**
	 * @param createById the createById to set
	 */
	public void setCreateById(String createById) {
		this.createById = createById;
	}

	/**
	 * @return the createdByName
	 */
	public String getCreatedByName() {
		return createdByName;
	}

	/**
	 * @param createdByName the createdByName to set
	 */
	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	/**
	 * @return the createdDate
	 */
	public String getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public String getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public String getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the beginLetter
	 */
	public String getBeginLetter() {
		return beginLetter;
	}

	/**
	 * @param beginLetter the beginLetter to set
	 */
	public void setBeginLetter(String beginLetter) {
		this.beginLetter = beginLetter;
	}

	/**
	 * @return the endLetter
	 */
	public String getEndLetter() {
		return endLetter;
	}

	/**
	 * @param endLetter the endLetter to set
	 */
	public void setEndLetter(String endLetter) {
		this.endLetter = endLetter;
	}

	/**
	 * @return the beginNumber
	 */
	public String getBeginNumber() {
		return beginNumber;
	}

	/**
	 * @param beginNumber the beginNumber to set
	 */
	public void setBeginNumber(String beginNumber) {
		this.beginNumber = beginNumber;
	}

	/**
	 * @return the endNumber
	 */
	public String getEndNumber() {
		return endNumber;
	}

	/**
	 * @param endNumber the endNumber to set
	 */
	public void setEndNumber(String endNumber) {
		this.endNumber = endNumber;
	}

	/**
	 * @return the categoryImage
	 */
	public byte[] getCategoryImage() {
		return categoryImage;
	}

	/**
	 * @param categoryImage the categoryImage to set
	 */
	public void setCategoryImage(byte[] categoryImage) {
		this.categoryImage = categoryImage;
	}

	/**
	 * @return the categoryImageName
	 */
	public String getCategoryImageName() {
		return categoryImageName;
	}

	/**
	 * @param categoryImageName the categoryImageName to set
	 */
	public void setCategoryImageName(String categoryImageName) {
		this.categoryImageName = categoryImageName;
	}

	/**
	 * @return the lotteryCategoryName
	 */
	public String getLotteryCategoryName() {
		return lotteryCategoryName;
	}

	/**
	 * @param lotteryCategoryName the lotteryCategoryName to set
	 */
	public void setLotteryCategoryName(String lotteryCategoryName) {
		this.lotteryCategoryName = lotteryCategoryName;
	}

	/**
	 * @return the effectiveDate
	 */
	public String getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * @param effectiveDate the effectiveDate to set
	 */
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * @return the subcategoryEffectiveDate
	 */
	public String getSubcategoryEffectiveDate() {
		return subcategoryEffectiveDate;
	}

	/**
	 * @param subcategoryEffectiveDate the subcategoryEffectiveDate to set
	 */
	public void setSubcategoryEffectiveDate(String subcategoryEffectiveDate) {
		this.subcategoryEffectiveDate = subcategoryEffectiveDate;
	}

	/**
	 * @return the lotteryNumber
	 */
	public String getLotteryNumber() {
		return lotteryNumber;
	}

	/**
	 * @param lotteryNumber the lotteryNumber to set
	 */
	public void setLotteryNumber(String lotteryNumber) {
		this.lotteryNumber = lotteryNumber;
	}

	/**
	 * @return the batchStatus
	 */
	public String getBatchStatus() {
		return batchStatus;
	}

	/**
	 * @param batchStatus the batchStatus to set
	 */
	public void setBatchStatus(String batchStatus) {
		this.batchStatus = batchStatus;
	}

	public Integer getSalePrice() {
		return salePrice;
	}

	public void setSalePrice(Integer salePrice) {
		this.salePrice = salePrice;
	}
	
}
