package com.gun.common.entity.pojo;
// Generated 2017-7-5 9:47:48 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.gun.common.pojo.ValueObject;

/**
 * AndroidUser generated by hbm2java
 */
public class OrderRecordDTO extends ValueObject<BigDecimal> {

	/**
	 * 序列号
	 */
	private static final long serialVersionUID = -6160353029859084663L;
	
	public static enum ATTRIBUTE {
		ORDER_NUMBER("orderNumber"),
		ANDROID_USER_ID("androidUserId"),
		ORDER_AMOUNT("orderAmount"),
		ROUND("round"),
		CATEGORY("category"),
		CREATED_DATE("createdDate");
		private String value;
		ATTRIBUTE(String value) {
			this.value = value;
		};
		public String getValue() {
			return this.value;
		}
	}
	
	private String orderNumber;//订单号
	private BigDecimal androidUserId;//用户id
	private BigDecimal orderAmount;//交易金额
	private Date createdDate;//创建时间
	private String round;
	private String category;
	private BigDecimal winninSum;
	private String periodState;
	private List<OrderRecordDetailsDTO> orderRecordDetailsDTOs;
	
	/**
	 * Constructor:无参构造
	 */
	public OrderRecordDTO() {
		
	}

	/**
	 * Constructor:有参构造
	 */
	public OrderRecordDTO(String orderNumber, BigDecimal androidUserId,
			BigDecimal orderAmount, Date createdDate) {
		super();
		this.orderNumber = orderNumber;
		this.androidUserId = androidUserId;
		this.orderAmount = orderAmount;
		this.createdDate = createdDate;
	}

	public BigDecimal getWinninSum() {
		return winninSum;
	}

	public void setWinninSum(BigDecimal winninSum) {
		this.winninSum = winninSum;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getRound() {
		return round;
	}

	public void setRound(String round) {
		this.round = round;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * @return the orderNumber
	 */
	public String getorderNumber() {
		return orderNumber;
	}

	/**
	 * @param orderNumber the orderNumber to set
	 */
	public void setorderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	/**
	 * @return the androidUserId
	 */
	public BigDecimal getAndroidUserId() {
		return androidUserId;
	}

	/**
	 * @param androidUserId the androidUserId to set
	 */
	public void setAndroidUserId(BigDecimal androidUserId) {
		this.androidUserId = androidUserId;
	}

	/**
	 * @return the orderAmount
	 */
	public BigDecimal getOrderAmount() {
		return orderAmount;
	}

	/**
	 * @param orderAmount the orderAmount to set
	 */
	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getPeriodState() {
		return periodState;
	}

	public void setPeriodState(String periodState) {
		this.periodState = periodState;
	}

	public List<OrderRecordDetailsDTO> getOrderRecordDetailsDTOs() {
		return orderRecordDetailsDTOs;
	}

	public void setOrderRecordDetailsDTOs(
			List<OrderRecordDetailsDTO> orderRecordDetailsDTOs) {
		this.orderRecordDetailsDTOs = orderRecordDetailsDTOs;
	}
	
}
