package com.gun.common.entity.pojo;
// Generated 2017-7-26 14:14:41 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

import com.gun.common.pojo.ValueObject;

/**
 * OrderRecordDetails generated by hbm2java
 */
public class OrderRecordDetailsDTO extends ValueObject<BigDecimal> {


	/**
	 * 
	 */
	private static final long serialVersionUID = -6568524447997493272L;
	public static enum ATTRIBUTE {
		ID("id"),
		ORDER_NUMBER("orderNumber"),
		LOTTERY_ROUND("lotteryRound"),
		LOTTERY_NUMBER("lotteryNumber"),
		WINNIN_GRADE("winninGrade"),
		WINNIN_SUM("winninSum");
		private String value;
		ATTRIBUTE(String value) {
			this.value = value;
		};
		public String getValue() {
			return this.value;
		}
	}
	
	
	
	private String orderNumber;
	private String lotteryRound;
	private String lotteryNumber;
	private BigDecimal winninSum;
	private Date createdDate;
	private String updatedById;
	private String updatedByName;
	private Date updatedDate;
	private String androidUserName;
	private BigDecimal androidUserId;
	private String winninName;
	private Integer winninGrade;
	

	public OrderRecordDetailsDTO() {
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getLotteryRound() {
		return lotteryRound;
	}

	public void setLotteryRound(String lotteryRound) {
		this.lotteryRound = lotteryRound;
	}

	public String getLotteryNumber() {
		return lotteryNumber;
	}

	public void setLotteryNumber(String lotteryNumber) {
		this.lotteryNumber = lotteryNumber;
	}

	public BigDecimal getWinninSum() {
		return winninSum;
	}

	public void setWinninSum(BigDecimal winninSum) {
		this.winninSum = winninSum;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedById() {
		return updatedById;
	}

	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	public String getUpdatedByName() {
		return updatedByName;
	}

	public void setUpdatedByName(String updatedByName) {
		this.updatedByName = updatedByName;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getAndroidUserName() {
		return androidUserName;
	}

	public void setAndroidUserName(String androidUserName) {
		this.androidUserName = androidUserName;
	}

	public BigDecimal getAndroidUserId() {
		return androidUserId;
	}

	public void setAndroidUserId(BigDecimal androidUserId) {
		this.androidUserId = androidUserId;
	}

	public String getWinninName() {
		return winninName;
	}

	public void setWinninName(String winninName) {
		this.winninName = winninName;
	}
	
	public Integer getWinninGrade() {
		return winninGrade;
	}

	public void setWinninGrade(Integer winninGrade) {
		this.winninGrade = winninGrade;
	}

}
