package com.gun.common.entity.pojo;

// Generated 2017/7/4 上午 09:29:23 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.gun.common.pojo.ValueObject;

/**
 * Period generated by hbm2java
 */
public class PeriodDTO  extends ValueObject<BigDecimal> {

	 /**
	 * 序列号
	 */
	private static final long serialVersionUID = -2316664363375293334L;
	//枚举
	public static enum ATTRIBUTE {
			ID("id"),
			ON_SALE("onSale"),
			OFF_SALE("offSale"),
			PERIOD("period"),
			PERIOD_STATE("periodState"),
			WINNIN_POSTER("winninPoster"),
			CREATE_BY_ID("createById"),
			CREATED_BY_NAME("createdByName"),
			CREATED_DATE("createdDate"),
			UPDATED_BY_ID("updatedById"),
			UPDATED_BY_NAME("updatedByName"),
			LOTTERY_TIMES("lotteryTimes"),
			APPROVE_STATE("approveState"),
			APPROVE_STATE_NAME("approveStateName"),
			LOTTERY_PERIODS("lotteryPeriods"),
			UPDATED_DATE("updatedDate"),
			IMAGE_URL("imageUrl"),
			LOTTERY_SALE_PRICE("lotterySalePrice"),
			SHOW_SALE_PRICE("showSalePrice")
		    ;
		    
		    private String value;
		    ATTRIBUTE(String value) {
		      this.value = value;
		    };
		    public String getValue() {
		      return this.value;
		    }
		  };
	private String period;
	private String periodState;
	private byte[] winninPoster;
	private String createById;
	private Serializable createdByName;
	private Date createdDate;
	private String updatedById;
	private Serializable updatedByName;
	private Date updatedDate;
	private String onSale;//开售日期
	private String offSale;
	private String lotteryTimes;
	private String approveState;
	private String approveStateName;
	private String imageUrl;
	private int lotterySalePrice;
	private int showSalePrice;;
	
	/**
	 * Constructor:无参构造
	 */
	public PeriodDTO() {
		super();
	}

	/**
	 * Constructor:有参构造
	 */
	public PeriodDTO(String period, String periodState, byte[] winninPoster, String createById,
			Serializable createdByName, Date createdDate, String updatedById, Serializable updatedByName,int lotterySalePrice,
			Date updatedDate, String onSale, String offSale, String lotteryTimes, String approveState,String approveStateName,String imageUrl) {
		super();
		this.period = period;
		this.periodState = periodState;
		this.winninPoster = winninPoster;
		this.createById = createById;
		this.createdByName = createdByName;
		this.createdDate = createdDate;
		this.updatedById = updatedById;
		this.updatedByName = updatedByName;
		this.updatedDate = updatedDate;
		this.onSale = onSale;
		this.offSale = offSale;
		this.lotteryTimes = lotteryTimes;
		this.approveState = approveState;
		this.approveStateName = approveStateName;
		this.imageUrl = imageUrl;
		this.lotterySalePrice = lotterySalePrice;
	}

	/**
	 * @return the period
	 */
	public String getPeriod() {
		return period;
	}

	/**
	 * @param period the period to set
	 */
	public void setPeriod(String period) {
		this.period = period;
	}

	/**
	 * @return the periodState
	 */
	public String getPeriodState() {
		return periodState;
	}

	/**
	 * @param periodState the periodState to set
	 */
	public void setPeriodState(String periodState) {
		this.periodState = periodState;
	}

	/**
	 * @return the winninPoster
	 */
	public byte[] getWinninPoster() {
		return winninPoster;
	}

	/**
	 * @param winninPoster the winninPoster to set
	 */
	public void setWinninPoster(byte[] winninPoster) {
		this.winninPoster = winninPoster;
	}

	/**
	 * @return the createById
	 */
	public String getCreateById() {
		return createById;
	}

	/**
	 * @param createById the createById to set
	 */
	public void setCreateById(String createById) {
		this.createById = createById;
	}

	/**
	 * @return the createdByName
	 */
	public Serializable getCreatedByName() {
		return createdByName;
	}

	/**
	 * @param createdByName the createdByName to set
	 */
	public void setCreatedByName(Serializable createdByName) {
		this.createdByName = createdByName;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the updatedById
	 */
	public String getUpdatedById() {
		return updatedById;
	}

	/**
	 * @param updatedById the updatedById to set
	 */
	public void setUpdatedById(String updatedById) {
		this.updatedById = updatedById;
	}

	/**
	 * @return the updatedByName
	 */
	public Serializable getUpdatedByName() {
		return updatedByName;
	}

	/**
	 * @param updatedByName the updatedByName to set
	 */
	public void setUpdatedByName(Serializable updatedByName) {
		this.updatedByName = updatedByName;
	}

	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the onSale
	 */
	public String getOnSale() {
		return onSale;
	}

	/**
	 * @param onSale the onSale to set
	 */
	public void setOnSale(String onSale) {
		this.onSale = onSale;
	}

	/**
	 * @return the offSale
	 */
	public String getOffSale() {
		return offSale;
	}

	/**
	 * @param offSale the offSale to set
	 */
	public void setOffSale(String offSale) {
		this.offSale = offSale;
	}

	/**
	 * @return the lotteryTimes
	 */
	public String getLotteryTimes() {
		return lotteryTimes;
	}

	/**
	 * @param lotteryTimes the lotteryTimes to set
	 */
	public void setLotteryTimes(String lotteryTimes) {
		this.lotteryTimes = lotteryTimes;
	}

	/**
	 * @return the approveState
	 */
	public String getApproveState() {
		return approveState;
	}

	/**
	 * @param approveState the approveState to set
	 */
	public void setApproveState(String approveState) {
		this.approveState = approveState;
	}

	/**
	 * @return the approveStateName
	 */
	public String getApproveStateName() {
		return approveStateName;
	}

	/**
	 * @param approveStateName the approveStateName to set
	 */
	public void setApproveStateName(String approveStateName) {
		this.approveStateName = approveStateName;
	}
	
	/**
	 * @return the imageUrl
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * @param imageUrl the imageUrl to set
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * @return the lotterySalePrice
	 */
	public int getLotterySalePrice() {
		return lotterySalePrice;
	}

	/**
	 * @param lotterySalePrice the lotterySalePrice to set
	 */
	public void setLotterySalePrice(int lotterySalePrice) {
		this.lotterySalePrice = lotterySalePrice;
	}

	public int getShowSalePrice() {
		return showSalePrice;
	}

	public void setShowSalePrice(int showSalePrice) {
		this.showSalePrice = showSalePrice;
	}

}
