package com.gun.common.entity.pojo;
// Generated 2017-6-1 18:10:41 by Hibernate Tools 4.0.1.Final

import java.util.Date;

import com.gun.common.entity.SysUserInfo;
import com.gun.common.pojo.ValueObject;

/**
 * SysUserInfo generated by hbm2java
 */
public class SysUserInfoDTO extends ValueObject<Integer> {

  private static final long serialVersionUID = -2821021314409889777L;
  
  public static enum ATTRIBUTE {
    ID("id"),
    USER_ID("userId"),
    USER_NAME("userName"),
    EMAIL("email"),
    LAST_LOGIN_TIME("lastLogintime"),
    PASSWORD("password"),
    ROLE_ID("roleId"),
    TELEPHONE("telephone"),
    CREATE_BY_ID("createById"),
    CREATED_BY_NAME("createdByName"),
    CREATED_DATE("createdDate"),
    UPDATED_BYID("updatedById"),
    UPDATED_BY_NAME("updatedByName"),
    UPDATED_DATE("updatedDate")
    ;
    
    private String value;
    ATTRIBUTE(String value) {
      this.value = value;
    };
    public String getValue() {
      return this.value;
    }
  };
  private String userId;
  private String userName;
  private String email;
  private String lastLogintime;
  private String password;
  private Integer roleId;
  private String telephone;
  private String createById;
  private String createdByName;
  private Date createdDate;
  private String updatedById;
  private String updatedByName;
  private Date updatedDate;
  private String roleName;

  public SysUserInfoDTO() {
  }

  public SysUserInfoDTO(String userId, String userName, String password, Integer roleId) {
    this.userId = userId;
    this.userName = userName;
    this.password = password;
    this.roleId = roleId;
  }
  public SysUserInfoDTO(String userId, String userName, String email, String lastLogintime, String password, Integer roleId, String telephone,
          String createById, String createdByName, Date createdDate, String updatedById, String updatedByName, Date updatedDate) {
    this.userId = userId;
    this.userName = userName;
    this.email = email;
    this.lastLogintime = lastLogintime;
    this.password = password;
    this.roleId = roleId;
    this.telephone = telephone;
    this.createById = createById;
    this.createdByName = createdByName;
    this.createdDate = createdDate;
    this.updatedById = updatedById;
    this.updatedByName = updatedByName;
    this.updatedDate = updatedDate;
  }

  public String getUserId() {
    return this.userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }
  public String getUserName() {
    return this.userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }
  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }
  public String getLastLogintime() {
    return this.lastLogintime;
  }

  public void setLastLogintime(String lastLogintime) {
    this.lastLogintime = lastLogintime;
  }
  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }
  public Integer getRoleId() {
    return this.roleId;
  }

  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }
  public String getTelephone() {
    return this.telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }
  public String getCreateById() {
    return this.createById;
  }

  public void setCreateById(String createById) {
    this.createById = createById;
  }
  public String getCreatedByName() {
    return this.createdByName;
  }

  public void setCreatedByName(String createdByName) {
    this.createdByName = createdByName;
  }
  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }
  public String getUpdatedById() {
    return this.updatedById;
  }

  public void setUpdatedById(String updatedById) {
    this.updatedById = updatedById;
  }
  public String getUpdatedByName() {
    return this.updatedByName;
  }

  public void setUpdatedByName(String updatedByName) {
    this.updatedByName = updatedByName;
  }
  public Date getUpdatedDate() {
    return this.updatedDate;
  }

  public void setUpdatedDate(Date updatedDate) {
    this.updatedDate = updatedDate;
  }

  public String getRoleName() {
    return roleName;
  }
  
  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }

  public SysUserInfo transformer(SysUserInfo sysUserInfo){
		if (sysUserInfo == null){
			sysUserInfo = new SysUserInfo();
		}
		sysUserInfo.setId(this.getId());
		sysUserInfo.setUserId(this.userId);
		sysUserInfo.setUserName(this.userName);
		sysUserInfo.setPassword(this.password);
		sysUserInfo.setEmail(this.email);
//		sysUserInfo.setPasswordSalt(this.passwordSalt);
		sysUserInfo.setCreateById(this.createById);
		sysUserInfo.setCreatedByName(this.createdByName);
		sysUserInfo.setCreatedDate(this.createdDate);
		sysUserInfo.setUpdatedById(this.updatedById);
		sysUserInfo.setUpdatedByName(this.updatedByName);
		sysUserInfo.setUpdatedDate(this.updatedDate);
		return sysUserInfo;
	}
  
}
