package com.gun.common.entity.pojo;
// Generated 2017-7-5 9:47:48 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

import com.gun.common.pojo.ValueObject;

/**
 * AndroidUser generated by hbm2java
 */
public class TopUpRecordDTO extends ValueObject<BigDecimal> {

	/**
	 * 序列号
	 */
	private static final long serialVersionUID = 4833879652635778207L;

	public static enum ATTRIBUTE {
		ANDROID_USER_ID("androidUserId"),
		DEALER_ID("dealerId"),
		DEALER_NAME("dealerName"),
		TOP_UP_AMOUNT("topUpAmount"),
		USERNAME("userName"),
		STATE("state"),
		CREATED_DATE("createdDate");
		private String value;
		ATTRIBUTE(String value) {
			this.value = value;
		};
		public String getValue() {
			return this.value;
		}
	}
	
	private String androidUserPhone;//用户手机号
	private BigDecimal androidUserId;//用户ID
	private Integer dealerId;
	private BigDecimal topUpAmount;//充值金额
	private Date createdDate;//创建时间
	private String userName;//用户号码
	private String fullName;
	private String dealerName;//商户名称
	private String state;//交易类型（状态）
	
	/**
	 * Constructor:无参构造
	 */
	public TopUpRecordDTO() {
		
	}

	/**
	 * Constructor:有参构造
	 */
	public TopUpRecordDTO(String androidUserPhone, BigDecimal androidUserId,
			Integer dealerId, BigDecimal topUpAmount, Date createdDate,
			String userName, String dealerName, String state) {
		super();
		this.androidUserPhone = androidUserPhone;
		this.androidUserId = androidUserId;
		this.dealerId = dealerId;
		this.topUpAmount = topUpAmount;
		this.createdDate = createdDate;
		this.userName = userName;
		this.dealerName = dealerName;
		this.state = state;
	}
	
	/**
	 * @return the androidUserId
	 */
	public BigDecimal getAndroidUserId() {
		return androidUserId;
	}

	/**
	 * @param androidUserId the androidUserId to set
	 */
	public void setAndroidUserId(BigDecimal androidUserId) {
		this.androidUserId = androidUserId;
	}

	/**
	 * @return the topUpAmount
	 */
	public BigDecimal getTopUpAmount() {
		return topUpAmount;
	}

	/**
	 * @param topUpAmount the topUpAmount to set
	 */
	public void setTopUpAmount(BigDecimal topUpAmount) {
		this.topUpAmount = topUpAmount;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the androidUserPhone
	 */
	public String getAndroidUserPhone() {
		return androidUserPhone;
	}

	/**
	 * @param androidUserPhone the androidUserPhone to set
	 */
	public void setAndroidUserPhone(String androidUserPhone) {
		this.androidUserPhone = androidUserPhone;
	}

	/**
	 * @return the dealerId
	 */
	public Integer getDealerId() {
		return dealerId;
	}

	/**
	 * @param dealerId the dealerId to set
	 */
	public void setDealerId(Integer dealerId) {
		this.dealerId = dealerId;
	}

	/**
	 * @return the username
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param phoneNo the phoneNo to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the dealerName
	 */
	public String getDealerName() {
		return dealerName;
	}

	/**
	 * @param dealerName the dealerName to set
	 */
	public void setDealerName(String dealerName) {
		this.dealerName = dealerName;
	}
	
	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	
	
}
