package com.gun.common.entity.pojo;
// Generated 2017-6-1 18:10:41 by Hibernate Tools 4.0.1.Final

import java.util.Date;

import com.gun.common.pojo.ValueObject;

/**
 * UserFeedback generated by hbm2java
 */
public class UserFeedbackDTO extends ValueObject<Integer> {

	/**
	 * 序列号
	 */
	private static final long serialVersionUID = -3429749260738908677L;
	
	//枚举
	public static enum ATTRIBUTE {
		ID("id"),
		SUGGESTION("suggestion"),
		MOBILE_NO("mobileNo"),
		DEAL_NAME("dealName"),
		DEAL_STATUS("dealStatus")
	    ;
	    private String value;
	    ATTRIBUTE(String value) {
	      this.value = value;
	    };
	    public String getValue() {
	      return this.value;
	    }
	};
	
	private String suggestion;//建议
	private String mobileNo;//电话
	private String dealStatus;//处理状态.
	private String dealName;
	private Date createdDate;
	
	/**
	 * Constructor:无参构造
	 */
	public UserFeedbackDTO() {
		super();
	}

	/**
	 * Constructor:有参构造
	 */
	public UserFeedbackDTO(String suggestion, String mobileNo, String dealStatus,
			String dealName, Date createdDate) {
		super();
		this.suggestion = suggestion;
		this.mobileNo = mobileNo;
		this.dealStatus = dealStatus;
		this.createdDate = createdDate;
		this.dealName = dealName;
	}

	/**
	 * @return the suggestion
	 */
	public String getSuggestion() {
		return suggestion;
	}

	/**
	 * @param suggestion the suggestion to set
	 */
	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

	/**
	 * @return the mobileNo
	 */
	public String getMobileNo() {
		return mobileNo;
	}

	/**
	 * @param mobileNo the mobileNo to set
	 */
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	/**
	 * @return the dealStatus
	 */
	public String getDealStatus() {
		return dealStatus;
	}

	/**
	 * @param dealStatus the dealStatus to set
	 */
	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the dealName
	 */
	public String getDealName() {
		return dealName;
	}

	/**
	 * @param dealName the dealName to set
	 */
	public void setDealName(String dealName) {
		this.dealName = dealName;
	}
	
}
